### ISSUE TITLE
Scheduled subscription update not allowing customer changes in billing portal

### ISSUE THREAD

**Issue by Lwonderg** [stripe/stripe-firebase-extensions#158] opened 2021-03-23 08:47 UTC
# Bug report

firestore-stripe-subscriptions

## Describe the bug

After making a manual scheduled subscription update in stripe, the billing portal still says there is a scheduled subscription update even after the scheduled update has been applied. This prevents customer from being able to change their plan, or cancel.

## To Reproduce

1. Schedule a future subscription update/change for a customer in stripe.
2. Wait for the update to apply on the scheduled date.
3. Customer visits the portal to change or cancel plan but is unable to.

## Expected behavior

After the scheduled subscription update the billing portal should allow customers to make their own changes or cancelations.

**Comment by thorsten-stripe** [comment] 2021-03-25 14:15
This sounds like an issue with the Stripe customer portal, but not the extension itself. I will forward this to the relevant team, but close it out here as it's not a bug with the extension.

**Closed by thorsten-stripe** 2021-03-25 14:15 UTC

**Comment by thorsten-stripe** [comment] 2021-04-06 04:57
@Lwonderg This has now been fixed! Customers will be able update their subscriptions through the Customer Portal when there's no future Phases on the attached Schedule.

Thanks again for reporting it!
