### ISSUE TITLE
Direct Payments ability

### ISSUE THREAD

**Issue by dannycortesv** [stripe/stripe-firebase-extensions#349] opened 2022-02-15 14:04 UTC
Would be great to have direct payment ability, we are building a marketplace where people create courses and sell them to their community, we would like them to receive payments from their students, any plan for this? Or any guide on how to use current extension to support it?

**Comment by DCSnip3r** [comment] 2022-02-15 17:07
You are describing stripe connect, which is discussed here https://github.com/stripe/stripe-firebase-extensions/issues/184

**Comment by jsteele-stripe** [comment] 2022-02-16 09:29
Closing as a duplicate of #184.

**Closed by jsteele-stripe** 2022-02-16 09:29 UTC
