### ISSUE TITLE
Passing Coupon Code in the request.

### ISSUE THREAD

**Issue by harjeetbackup** [stripe/stripe-firebase-extensions#129] opened 2021-01-27 16:36 UTC
# Ability to add send a coupon Code or Coupon ID in the Request Post so that coupon is automatically applied to the checkout page

- Extension name: [e.g. `firestore-stripe-subscriptions`, or leave empty if suggesting a new extension]

## Is your feature request related to a problem? Please describe.

We dont want a user to enter the code in the Add promo code field. It should be prepopulated id we send a coupon ID see below code in this case we can show the add Promotion code field and user has to manually enter it. We would like to show it automatically applied if we pass the coupon code request so user will not have to type it. See my line of suggested request we can make

{
  "payment_method_types": {
    "0": "card"
  },
  "customer": "cus_Ipvy0VXlaqrpNk",
  "line_items": {
    "0": {
      "price": "price_1HelGOKlaLxm3MKPOAzXb70A",
      "quantity": "1"
    }
  },
  "mode": "subscription",
  "allow_promotion_codes": "true",
//We should have ability to send Coupon_ID here which will auto populate the add Promotion code field on checkout form. One less step for the user
  "subscription_data": {
    "trial_from_plan": "true"
  },
  "success_url": "http://localhost:5000/subscribe.html?via=harjeetbackup&scs=1",
  "cancel_url": "http://localhost:5000/subscribe.html?via=harjeetbackup"
}

**Comment by thorsten-stripe** [comment] 2021-01-28 15:35
Duplicate of https://github.com/stripe/stripe-firebase-extensions/issues/107

**Closed by thorsten-stripe** 2021-01-28 15:35 UTC
