### ISSUE TITLE
Creating separate charges and transfers

### ISSUE THREAD

**Issue by dancixx** [stripe/stripe-firebase-extensions#224] opened 2021-07-18 08:19 UTC
# Feature request
- Extension name: firestore-stripe-subscriptions

## Is your feature request related to a problem? Please describe.
Creating separate charges and transfers

We are building a platform where others can sell their products and would be great if we can create separate charges immediately after the purchase.  

## Describe the solution you'd like

Basic stripe solution for separate charges and transfers.
https://stripe.com/docs/connect/charges-transfers

**Comment by thorsten-stripe** [comment] 2021-07-29 16:08
Stripe connect is currently out of scope for this extension. Will leave this issue open to track broader interest, though.

**Comment by jsteele-stripe** [comment] 2022-02-16 09:33
Closing as a duplicate of #184.

**Closed by jsteele-stripe** 2022-02-16 09:33 UTC
Labels: enhancement
