### ISSUE TITLE
Support for volume pricing model

### ISSUE THREAD

**Issue by kermitdefroghere** [stripe/stripe-firebase-extensions#335] opened 2022-01-07 19:19 UTC
Is there an intent to support Stripe's volume pricing model?

The ability for subscribers to pay tiered pricing for items in high volume would be very useful for our use case.

**Comment by kermitdefroghere** [comment] 2022-02-16 15:15
For a product, Stripe offers 4 different Pricing models:  Standard, Packaged, Graduated and Volume. Unless something has changed since January, the Firebase extension for Stripe does not support the Volume pricing model. We create platforms for industries that have clients with potentially hundreds of staff (or more). We'd like to be able to use the Volume pricing model so clients can easily get tiered pricing based on the quantity of staff they employ. (First 10 users at price X. 10-50 users at price Y. 50-100 users at price Z, etc)

**Comment by batical** [comment] 2022-05-02 18:29
I second this request. So for now we have to do it manually ?

**Comment by jsteele-stripe** [comment] 2022-07-27 16:09
@kermitdefroghere @batical volume pricing should be supported (you just pass your volume base Price object as a line item).

I guess the issue is that your users can't adjust the line item quantity to reflect the volume they want on the payment page?

**Comment by DCSnip3r** [comment] 2022-07-27 17:28
> 

@jsteele-stripe Not sure if this is what you are saying (I'm confused by this issue), but I personally would not want quantity configuration added on stripe checkout payment page. Quantity is determined when creating the checkout session, and I want to be able to restrict purchasable quantities to certain intervals on my checkout page. 

I don't understand this issue. When creating my products, I use these params to create my plans, and volume pricing works fine. I don't understand why a change is needed.
```
        billing_scheme: "tiered",
        tiers_mode: "volume",
```

**Comment by jsteele-stripe** [comment] 2022-07-27 19:21
@DCSnip3r I'm not sure a change is needed either. I'm just trying to understand the issue that is currently blocking the other users :)

**Comment by kermitdefroghere** [comment] 2022-07-27 19:45
I just checked the stripe-firebase-extension instructions and volume pricing still doesn't appear to be supported.
(https://github.com/stripe/stripe-firebase-extensions/blob/master/firestore-stripe-payments/POSTINSTALL.md)

"The extension currently supports pricing plans that bill a predefined amount at a specific interval. More complex plans (e.g. different pricing tiers or seats) are not yet supported. If you'd like to see support for these, please open a [feature request issue](https://github.com/stripe/stripe-firebase-extensions/issues/new/choose) with details about your business model and pricing plans."

**Comment by DCSnip3r** [comment] 2022-07-27 20:19
Is this just outdated documentation? I might remember a time when this feature was not available, but then was resolved.

I already can use subscription plans with quantity-based-tiers successfully
        billing_scheme: "tiered",
        tiers_mode: "volume",

Am I getting confused by terminology?

I cannot speak to whether seat-based pricing works, haven't tried it.

**Comment by jsteele-stripe** [comment] 2022-07-29 08:40
Closing this out as it volume prices are supported by both Checkout and this extension. Please re-open with a replication if you're encountering a specific issue.

**Closed** 2022-07-29 08:40 UTC
Labels: awaiting author feedback
