### ISSUE TITLE
Custom claim not working with metered billing

### ISSUE THREAD

**Issue by t-kaufmann** [stripe/stripe-firebase-extensions#148] opened 2021-03-04 09:50 UTC
# Bug report

firestore-stripe-subscriptions

## Describe the bug

Subscribing to a metered billing product via Stripe Checkout does not set a custom claim on the user.

## To Reproduce

1. Create a Stripe product with metered billing enabled
2. Set a firebaseRole in metadata
3. Subscribe to the product via Stripe Checkout

## Expected behavior

The extension should set a custom claim on the user, like it is done with products where metered billing is disabled

## Screenshots

N.A.

## System information

- OS: Windows
- Browser: Chrome

## Additional context

N.A.

**Comment by thorsten-stripe** [comment] 2021-03-04 09:53
This is a duplicate of https://github.com/stripe/stripe-firebase-extensions/issues/138 and has been fixed in v0.1.11. Unfortunately Firebase has not yet deployed said version, sorry!

I'll keep this open until v0.1.11 has been deployed

**Closed** 2021-03-08 02:52 UTC
Labels: bug
