### ISSUE TITLE
[FAQ] Existing Stripe Customers Not Syncing

### ISSUE THREAD

**Issue by thisisvilla** [stripe/stripe-firebase-extensions#97] opened 2020-11-09 17:22 UTC
# Bug report

- Extension name: `firestore-stripe-subscriptions`

## Describe the bug

I already have firebase & stripe customers that were synced with a custom webhook. 
I am trying to replace that piece of infrastructure with this extension, but it doesn't seem there is anyway to force a sync for the existing customers.

## Expected behavior

Some path to syncing existing customers, possibly by their user email.

Thank youuuuu :)

**Comment by thorsten-stripe** [comment] 2020-11-10 04:39
Duplicate of https://github.com/stripe/stripe-firebase-extensions/issues/93#issuecomment-723879491

Leaving this open as a reminder that I need to make it clearer that the extension creates customer objects as needed on the fly and there is no need to backfill existing users.

**Comment by thisisvilla** [comment] 2020-11-10 16:05
@thorsten-stripe thanks for your reply! I'm still a little confused about this... I understand it creates new customers in stripe for new firebase users, but all my existing firebase users and stripe customers are not syncing. 

The problem is, I have gated content that checks if a users plan is active in the collections created by this extension. So for new users it works fine, but pre-existing users don't have those documents/collections generated, does that make sense?

Thanks in advance!! It's so great to be able to have an even leaner infrastructure by outsourcing the stripe functionality from a custom api to this extension!

**Comment by thorsten-stripe** [comment] 2020-11-16 04:00
@thisisvilla are you saying you have existing customers in Stripe with existing subscriptions? The extension is not able to sync these, but rather you will need to add your existing Stripe customer ID to the user doc in your Cloud Firestore:
![image](https://user-images.githubusercontent.com/23213994/99211380-2672c200-2803-11eb-9473-ecf3a5fc7dd4.png)

As long as you have the `stripeId` set in your user doc, the extension will use this customer ID for that user. Otherwise it will create a new Stripe customer object.

**Comment by thisisvilla** [comment] 2020-11-18 00:10
@thorsten-stripe Thanks for your reply! Yeah, I found that work-around, but I also had to add the 'firebaseUID' meta key to the customer in stripe, as well as do some arbitrary update to the user's subscription. Then everything synced just fine! Thanks!! Keep up the great work! 🎉

**Comment by thorsten-stripe** [comment] 2020-11-18 04:11
@thisisvilla glad you got it working. The `firebaseUID` metadata should not be required, it's just there to make searching in the dashboard more convenient.

**Closed by thorsten-stripe** 2020-11-18 04:11 UTC
Labels: documentation
