### ISSUE TITLE
Add non-card payment methods

### ISSUE THREAD

**Issue by Spitzbua** [stripe/stripe-firebase-extensions#153] opened 2021-03-11 09:04 UTC
# Bug report

Adding other payment method types than "card" results in this error message "The payment method `sofort` cannot be used in `subscription` mode.".

## Describe the bug

I have added other payment method types which supports recurring payments like (ideal,sofort,sepa_debit). In the end I have tried all available ones (['card', 'sepa_debit','eps','sofort','bancontact','giropay','p24','ideal']). Card is the only payment method type which is working. The stripe support stated that 'sofort' and 'sepa_debit' should be functional too.

## To Reproduce

Add any other payment method type than card to checkout_session:

const docRef = await db
  .collection('users')
  .doc(currentUser)
  .collection('checkout_sessions')
  .add({
    price: 'price_1GqIC8HYgolSBA35zoTTN2Zl',
    payment_method_types:['card','sofort']
    success_url: window.location.origin,
    cancel_url: window.location.origin,
  });

## Expected behavior

I have expected that all payment method type with recurring payments active should work.

## System information

- OS: Windows
- Browser Chrome

## Additional context

It would be advantageous for the developer or customer if the website clearly shows which payment methods work and are approved for subscriptions. I could not find any concrete information about this.

**Comment by eduardhildebrandt** [comment] 2021-03-17 16:10
+1

**Comment by thorsten-stripe** [comment] 2021-03-25 17:07
@Spitzbua sorry about this, I agree that it's not clear enough, we'll work on making it clearer in the docs.

For the time being, Stripe Checkout only supports cards in subscription mode. In order to use iDEAL etc, you would have to first implement https://stripe.com/docs/payments/ideal/set-up-payment and then subscribe the customer via the API https://stripe.com/docs/api/subscriptions/create

From that point on the extension can track the subscriptions and provide access to the customer portal.

Subscription mode support in Checkout for these methods is in planning, but I can't share a concrete timeline just yet, sorry.

**Comment by Spitzbua** [comment] 2021-05-06 07:11
@thorsten-stripe , thank you for your answer. 

One Time Payments were introduced with the release of 0.1.12 - 2021-04-29. Is it now possible to use payment methods other than Card in Payment Mode?

If not, what is the reason for this restriction or are there already plans to change this?

**Comment by thorsten-stripe** [comment] 2021-05-06 13:55
@Spitzbua non-card payment methods are supported in `payment` mode, but not yet in `subscription` mode.

This isn't a restriction by the extensions, but rather by Stripe Checkout itself. The team is working on enabling non-card payment methods in Stripe Checkout for `subscription` mode, and I will update here once supported.

**Comment by ehildebrandt** [comment] 2021-05-06 14:08
@thorsten-stripe Thank you for the update. SEPA payment is the most used payment method in Europe and we badly need this feature. I hope that Stripe Checkout team will support it soon. I'm looking forward to it. Thanks again.

**Comment by Spitzbua** [comment] 2021-05-06 15:03
@thorsten-stripe , thank you very much for your quick reply. highly appreciated!

Sorry for my confusion about that. Do I assume correctly if I configure a Checkout Sessions for one-time payments with referencing a one-time price ID the user will be redirected to the customer portal and has the choice between several active payment methods like SEPA and so on and not just payment method card? 

My thoughs from the [documentation ](https://stripe.com/docs/billing/subscriptions/integrating-customer-portal) were that these are limiations from the customer portal. There cannot be a default payment method because the user is created during the checkout.

> Payment method management functionality only supports cards. This section only displays cards, and it is hidden if the customer’s default payment method is not a card.

I totally agree with @ehildebrandt answers. Additionally many customers have problems with 3d secure during the card payment. If one-time payments are working as above mentioned it would be at least a workaround by offering a "one-time sub" until it is officialy supported.

**Comment by thorsten-stripe** [comment] 2021-05-06 15:20
> Sorry for my confusion about that. Do I assume correctly if I configure a Checkout Sessions for one-time payments with referencing a one-time price ID the user will be redirected to the customer portal and has the choice between several active payment methods like SEPA and so on and not just payment method card?

Not quite. The customer will be redirected to Stripe Checkout where they can pay for the one-time price by adding their IBAN. And they would have to reenter their IBAN for ever future payment.

But yes, for one time payments you can do:

```js
const checkoutSession = {
    collect_shipping_address: true,
    tax_rates: taxRates,
    allow_promotion_codes: true,
    line_items: [selectedPrice],
    success_url: window.location.origin,
    cancel_url: window.location.origin,
    metadata: {
      key: 'value',
    },
  };
  // For one time payments set mode to payment.
  if (prices[selectedPrice.price]?.type === 'one_time') {
    checkoutSession.mode = 'payment';
    checkoutSession.payment_method_types = ['card', 'sepa_debit', 'sofort'];
  }
```

**Comment by eduardhildebrandt** [comment] 2021-06-25 07:29
SEPA direct debit in subscription mode is now available as beta.
https://stripe.com/docs/billing/subscriptions/sepa-debit-subscription-mode

**Comment by thorsten-stripe** [comment] 2021-07-08 08:35
@eduardhildebrandt yes, if you're gated into that beta, you can provide `payment_method_types: ['card', 'sepa_debit'],` to your `checkout_sessions` doc creation to enable SEPA DD as payment method.

**Comment by eduardhildebrandt** [comment] 2021-07-09 15:46
@thorsten-stripe Yes, thank you. We already using stripe-firebase-extensions with SEPA since 28th June. It's looking good so far. We have multiple successful transactions. Our most painful issue is currently issue #177. Most of the German users fail their "3D Secure" verification on the first trial. In combination with issue #177 this usually results in a support case for us.

**Comment by cvoadmin** [comment] 2021-09-01 00:32
Hi @thorsten-stripe 
Same error, except we've been approved for recurring Alipay. The extension makes requests over the Charges API. In order to use the recurring Alipay feature, it must use the Setup Intents API instead.

**Comment by napter** [comment] 2022-01-01 23:54
@thorsten-stripe Was the feature ever added to checkout to use other payment methods in subscription mode? It seemed like this should be possibly from the docs but I get "The payment method cannot be used in subscription mode" error for anything other than 'card'. 

Any word on if this will be resolved or do we need to recreate checkout using elements or something to enable other payment types with subscriptions?

**Comment by cvoadmin** [comment] 2022-01-02 17:19
As of Version 0.2.3 all payment methods enabled in your Dash are presented in checkout, you no longer need to use `payment_method_types` in your scripts. 
Also Thorsten no longer works for Stripe.

**Comment by napter** [comment] 2022-01-02 17:28
@cvoadmin Version 0.2.3 of which library? I'm using Stripe Node, only commented here because it's the only place I saw this particular issue discussed but the issue above confirmed to be an issue with checkout, not of any particular library.

Are you sure that is true even when using checkout for subscriptions? If you try adding any other payment_method_types when using subscription it still gives the error "The payment method cannot be used in subscription mode" which would lead me to believe those methods would not show up in subscription mode even when left out.

Also, when creating a subscription checkout session and passing nothing for `payment_method_types` the checkout session returns `payment_method_types: [ 'card' ]` - it doesn't appear to be allowing any other types.

**Comment by cvoadmin** [comment] 2022-01-02 17:54
Just delete the whole line and enable other methods in dash. It's for all libraries.

**Comment by napter** [comment] 2022-01-02 18:49
I did this. The checkout session for subscriptions still returns
payment_method_types:
[ 'card' ] even when leaving the parameter off and enabling other methods
in the dash.

**Comment by Spitzbua** [comment] 2022-01-16 08:47
@napter , could you manage to use other payment method types but card in subscription mode?

**Comment by HerbertBodner** [comment] 2022-01-19 22:45
I specifically use `payment_method_types: []` in the firebase `checkout` database object. (using subscription mode)
But the firebase stripe extension still sends `payment_method_types: [ 'card' ]` to stripe. I can see that in the Stripe API logs.
Also removing this whole line has the same effect.

So I think the latest firebase extension (0.2.4) is still restricted to only card payments for subscription pricing.
@cvoadmin do you have any suggestions?

**Comment by cjavilla-stripe** [comment] 2022-01-28 10:13
We should be defaulting to automatic payment methods now, but aren't yet.

**Comment by paulmattu** [comment] 2022-02-04 10:40
not sure if i missed something but stripe doesnt support "sofort" payment in subscription mode
https://stripe.com/docs/payments/sofort/accept-a-payment
"sepa" works fine with stripe/firestore-stripe-payments@0.2.4 but I would also be happy about "sofort"

**Comment by jsteele-stripe** [comment] 2022-02-10 15:22
I'm unable to replicate this using `firebase-stripe-payments@0.2.4` – [this](https://github.com/stripe/stripe-firebase-extensions/pull/246) PR addressed the issue and was released in [`0.2.3`](https://github.com/stripe/stripe-firebase-extensions/blob/next/firestore-stripe-payments/CHANGELOG.md#version-023---2021-11-29). Checkout Sessions created with `mode: 'subscription'` don't contain the `payment_method_type` parameter and as such use automatic payment methods as detailed [here](https://stripe.com/docs/payments/dashboard-payment-methods). 

Please can you double check that you're using `>= 0.2.4` of the extension.

**Closed** 2022-02-11 15:01 UTC
Labels: bug, enhancement

**Comment by HerbertBodner** [comment] 2022-02-20 06:47
I double-checked the version and I am using `stripe/firestore-stripe-payments@0.2.4`. Still having the same issue.
I created a checkout session as follows:
```
this.db
            .collection('registeredUsers')
            .doc(firebaseId)
            .collection('checkout_sessions')
            .add({
                price: priceVal,
                success_url: successUrlVal,
                cancel_url: cancelUrlVal,
                allow_promotion_codes: true,
                automatic_tax: true,        // Automatically calculate tax based on the customer's address
                tax_id_collection: true,    // Collect the customer's tax ID (important for B2B transactions)
                mode: 'subscription',
                metadata: {
                    teamId: teamIdVal,
                    teamName: teamNameVal
                },
            });
```

In the stripe logs I receive the API call `POST v1/checkout/sessions` with the body containing:
```
...
  },
  "mode": "subscription",
  "payment_intent": null,
  "payment_link": null,
  "payment_method_options": null,
  "payment_method_types": [
    "card"
  ],
....
```  

I still see the `card` in the `payment_method_types`.

**Comment by jsteele-stripe** [comment] 2022-02-21 11:23
@HerbertBodner I'd recommend writing in to [support](https://support.stripe.com) so we can help you further. It's difficult to debug this further without any logs/account context.

**Comment by jsteele-stripe** [comment] 2022-02-23 10:42
@Spitzbua Why are you even passing `payment_method_types` in this instance if you're not providing a value?

> I have checked all available payment method types. Only card and sepa_debit can be used. Using another one leads to an error message that it cannot be used.

That's likely because some of those methods you've listed (namely EPS) don't support recurring payments. This is why relying on APMs is the clear path forward as Checkout will determine what payment methods to offer based on that unique session.

**Comment by jsteele-stripe** [comment] 2022-02-24 09:35
I misspoke. It's not the API, but the `stripe-node` client that removes any empty array/null values. So if you're passing `pyament_method_types: []` (for whatever reason) when creating your Firestore document, that parameter is essentially removed from the API call and we instead fallback to automatic payment methods.

**Comment by Spitzbua** [comment] 2022-02-24 16:28
@jsteele-stripe , thank you for your quick reply!
In previous versions of the integration, it was necessary to specify the payment methods because different payments are supported depending on the mode (OT payment, subscription).

If I use empty types payment_method_types: [], then only card payments (Austria preselected) are offered on Stripe Checkout. 
If this is sent then surely the automatic payment methods should be activated and all configured payment methods should be displayed? However, **SEPA debit is not visible.**

How should I enable SEPA-Debit by not setting payment_method_types ['card', 'sepa_debit']?

Specific question about SEBA-Debit: Does the status of the subscription automatically jump to 'trialing' or 'active' immediately after the checkout is completed (as with credit cards) or only after a few days when the payment has been made?

**Comment by jsteele-stripe** [comment] 2022-02-25 15:27
> In previous versions of the integration, it was necessary to specify the payment methods because different payments are supported depending on the mode (OT payment, subscription).

Yes, but that was before we added support for APMs. If you pass `payment_method_types: []` now, `stripe-node` will strip the parameter from the API request and you'll default to APMs.

> If this is sent then surely the automatic payment methods should be activated and all configured payment methods should be displayed? However, SEPA debit is not visible.

Whether SEPA Debit is shown depends on a variety of issues, including presentment currency and customer location. See [here](https://stripe.com/docs/payments/payment-methods/integration-options#payment-method-product-support).

> Specific question about SEBA-Debit: Does the status of the subscription automatically jump to 'trialing' or 'active' immediately after the checkout is completed (as with credit cards) or only after a few days when the payment has been made?

I'd recommend jumping into our [Discord server](https://stripe.com/go/developer-chat) to chat with Stripe engineers about integration questions not related to this extension!
