### ISSUE TITLE
New Trial API support

### ISSUE THREAD

**Issue by dancixx** [stripe/stripe-firebase-extensions#243] opened 2021-09-03 22:23 UTC
# Feature request

- `firestore-stripe-subscriptions`

## Is your feature request related to a problem? Please describe.

If I am not wrong this extension supports the old trial API when we added the trial period days to the price object. 
![Képernyőfotó 2021-09-04 - 0 21 53](https://user-images.githubusercontent.com/56868953/132070608-eefc8659-6a58-407f-9b25-d86cc46477fb.png)
But `Stripe` suggests that we should apply the `trial days` through the subscriptions or quotes.
![Képernyőfotó 2021-09-04 - 0 21 22](https://user-images.githubusercontent.com/56868953/132070571-e3b5c467-8e66-4e2e-ae41-8455ce852bd0.png)
This feature is compatible with the checkout sessions or should we wait for the support in this extension?

**Comment by thorsten-stripe** [comment] 2021-09-06 16:13
Duplicate of https://github.com/stripe/stripe-firebase-extensions/issues/105

**Comment by dancixx** [comment] 2021-09-06 16:31
@thorsten-stripe Thanks, I follow it and I'm sorry for the duplication, I was inattentive.

**Closed** 2021-09-06 16:31 UTC
