### ISSUE TITLE
Subscription Trial Days not Passed into subscription_data

### ISSUE THREAD

**Issue by atnegrete** [stripe/stripe-firebase-extensions#114] opened 2020-12-12 16:15 UTC
# Bug/Feature? report

- Please close one if this is considered a duplicate: https://github.com/stripe-samples/firebase-subscription-payments/issues/17

## Additional context
![image](https://user-images.githubusercontent.com/22260151/101989018-18c62600-3c63-11eb-8c13-c0fc83cbc2ba.png)

![image](https://user-images.githubusercontent.com/22260151/101988984-e3b9d380-3c62-11eb-96ea-9824673bd4f6.png)

**Comment by atnegrete** [comment] 2020-12-12 16:18
I can probably do a PR adding that field later today.. but not sure if the team still needs to consider updating documentation/other things around trial days, as it's not working in its current state.

**Comment by thorwebdev** [comment] 2020-12-12 16:22
It's working as expected on the demo: https://stripe-subs-ext.web.app/ (the premium yearly plan has a 1 day trial)![image](https://user-images.githubusercontent.com/5748289/101989115-2cac6f00-3cd9-11eb-9382-b40ba134d7f5.png)

Please double check that you've configured everything correctly.

**Comment by thorwebdev** [comment] 2020-12-12 16:24
trial period days should not be set on the client side as it means a user could extend their trial by modifying it. That's why we use trial from plan.

**Comment by thorwebdev** [comment] 2020-12-12 16:27
Duplicate of https://github.com/stripe/stripe-firebase-extensions/issues/105

**Comment by atnegrete** [comment] 2020-12-14 16:59
Thanks! Makes sense. Can't believe I didn't think of that lol I will check my configuration and report back 😀

**Comment by atnegrete** [comment] 2020-12-15 04:29
@thorwebdev  I've double checked everything, and nothing looks off. The extension is working flawlessly, aside from trials. I can't figure out what could be the issue. It's just a matter of setting the Trial Days field in the Price for a Product right? 

Also, did you temporarily add the 1 day trial on that demo app? Because it's not showing up for me. Thanks

**Comment by atnegrete** [comment] 2020-12-15 04:31
@thorwebdev I misunderstood the trial_from_plan field, I thought stripe would automatically handle not giving the trial again...!

**Closed** 2020-12-15 04:31 UTC
